# Generated by Django 5.1.6 on 2025-03-06 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='Followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
